/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

/**
 *
 * @author powji
 */
public class frmConteuro extends javax.swing.JDialog {

    /**
     * Creates new form frmConteuro
     */
    public frmConteuro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblConteudo2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConteudo1 = new javax.swing.JLabel();
        lblConteudo2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblConteudo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConteudo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Design sem nome.jpg"))); // NOI18N
        lblConteudo1.setAutoscrolls(true);
        lblConteudo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblConteudo1);
        lblConteudo1.setBounds(0, 110, 1525, 530);

        lblConteudo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConteudo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/O Curiosity foi o explorador mais equipado a ser lançado a marte quando pousou na cratera Gale em 6 de agosto de 2012, o rover é parte da missão Mars Science Laboratory da Nasa e está no planeta v.jpg"))); // NOI18N
        lblConteudo2.setMaximumSize(new java.awt.Dimension(540, 540));
        lblConteudo2.setMinimumSize(new java.awt.Dimension(540, 540));
        lblConteudo2.setPreferredSize(new java.awt.Dimension(540, 540));
        getContentPane().add(lblConteudo2);
        lblConteudo2.setBounds(0, 110, 1525, 530);

        btnVoltar.setBackground(new java.awt.Color(74, 43, 23));
        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(164, 127, 85));
        btnVoltar.setText("Anterior");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(605, 670, 130, 40);

        btnProximo.setBackground(new java.awt.Color(74, 43, 23));
        btnProximo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnProximo.setForeground(new java.awt.Color(164, 127, 85));
        btnProximo.setText("Proximo");
        btnProximo.setBorder(null);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProximo);
        btnProximo.setBounds(790, 670, 130, 40);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(null);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1275, 633, 180, 70);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        lblConteudo2.setVisible(true);
        lblConteudo1.setVisible(false);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        lblConteudo1.setVisible(true);
        lblConteudo2.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        frmNome frmN = new frmNome(null,true);
        this.setVisible(false);
        frmN.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConteuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConteuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConteuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConteuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConteuro dialog = new frmConteuro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblConteudo1;
    private javax.swing.JLabel lblConteudo2;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
