/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.*;
/**
 *
 * @author User
 */
public class frmFinal extends javax.swing.JDialog
{

    /**
     * Creates new form frmFinal
     */
    public frmFinal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        lblNome.setText(Estaticos.NOME);
        lblTotalRespo.setText(Estaticos.TEXTO);
        if(Estaticos.SOMAACERTOS >= 3){
            lblSituacao.setText("Parabens!!");
            lblAcertos.setText(Estaticos.ACERTOS);
                    }else
        {
            lblSituacao.setText("Que pena!");
            lblAcertos.setText(Estaticos.ACERTOS);
            
        }
        
        
        new java.util.Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                //executar ação aqui
            btnFinalizar.doClick();
            }
        }, 7000);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinalizar = new javax.swing.JButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        btnMostrarDados = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFinalizar.setBackground(new java.awt.Color(74, 43, 23));
        btnFinalizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(164, 127, 85));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorder(null);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, 150, 60));
        getContentPane().add(lblTotalRespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 917, 449, 20));

        lblNome.setBackground(new java.awt.Color(74, 43, 23));
        lblNome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(164, 127, 85));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("seu nome");
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 130, 1490, 40));

        lblAcertos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAcertos.setForeground(new java.awt.Color(164, 127, 85));
        lblAcertos.setText("total de acerto");
        getContentPane().add(lblAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 156, -1));

        lblSituacao.setBackground(new java.awt.Color(74, 43, 23));
        lblSituacao.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSituacao.setForeground(new java.awt.Color(164, 127, 85));
        lblSituacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituacao.setText("Parabéns!!");
        lblSituacao.setAlignmentY(0.0F);
        getContentPane().add(lblSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1525, 40));

        btnMostrarDados.setBackground(new java.awt.Color(74, 43, 23));
        btnMostrarDados.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMostrarDados.setForeground(new java.awt.Color(164, 127, 85));
        btnMostrarDados.setText("respostas ");
        btnMostrarDados.setBorder(null);
        btnMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 132, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinalizarActionPerformed
    {//GEN-HEADEREND:event_btnFinalizarActionPerformed
        frmInicial frmI = new frmInicial(null, true);
        this.setVisible(false);
        frmI.setVisible(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnMostrarDadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarDadosActionPerformed
    {//GEN-HEADEREND:event_btnMostrarDadosActionPerformed

    // Cria uma instância de StringBuilder para construir uma string 
        // StringBuilder é uma classe do pacote java.lang.
    StringBuilder sb = new StringBuilder(); 

    // Vai ate a lista de visitantes obtida pelo método estático getListaVisitantes()
    for (Visitantes visitante : Visitantes.getListaVisitantes()) 
    {
    // Adiciona a representação em string de cada visitante ao StringBuilder, seguida por uma nova linha
    sb.append(visitante.toString()).append("\n"); 
    }
    // Exibe uma caixa de diálogo com o conteúdo do StringBuilder, que contém as informações dos visitantes
    JOptionPane.showMessageDialog(null, sb); 

    }//GEN-LAST:event_btnMostrarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmFinal dialog = new frmFinal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMostrarDados;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTotalRespo;
    // End of variables declaration//GEN-END:variables
}
