/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

import javax.swing.JOptionPane;
import modelo.Controle;
import modelo.Visitantes;

/**
 *
 * @author User
 */
public class frmPergunta2 extends javax.swing.JDialog
{
    String resp2;
    String resp3;
    String resp4;
    String resp5;
    
    /**
     * Creates new form frmPergunta2
     */
    public frmPergunta2(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnP2 = new javax.swing.ButtonGroup();
        gbtnP3 = new javax.swing.ButtonGroup();
        gbtnP4 = new javax.swing.ButtonGroup();
        gbtnP5 = new javax.swing.ButtonGroup();
        lblPergunta2 = new javax.swing.JLabel();
        rbdP2A = new javax.swing.JRadioButton();
        rbdP2B = new javax.swing.JRadioButton();
        rbdP2C = new javax.swing.JRadioButton();
        lblPergunta3 = new javax.swing.JLabel();
        rbdP3B = new javax.swing.JRadioButton();
        rbdP3C = new javax.swing.JRadioButton();
        lblPergunta4 = new javax.swing.JLabel();
        rbdP4A = new javax.swing.JRadioButton();
        rbdP4B = new javax.swing.JRadioButton();
        rbdP4C = new javax.swing.JRadioButton();
        lblPergunta5 = new javax.swing.JLabel();
        rbdP5A = new javax.swing.JRadioButton();
        rbdP5B = new javax.swing.JRadioButton();
        rbdP5C = new javax.swing.JRadioButton();
        rbdP3A = new javax.swing.JRadioButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        lblMostrarResultado = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblacertos = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPergunta2.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPergunta2.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta2.setText("Pergunta 2: Qual foi o primeiro rover a pousar em Marte? ");
        getContentPane().add(lblPergunta2);
        lblPergunta2.setBounds(110, 60, 470, 21);

        rbdP2A.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2A);
        rbdP2A.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP2A.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2A.setText("a) Spirit");
        rbdP2A.setBorder(null);
        getContentPane().add(rbdP2A);
        rbdP2A.setBounds(120, 100, 110, 23);

        rbdP2B.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2B);
        rbdP2B.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP2B.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2B.setText("b) Perseverance");
        rbdP2B.setBorder(null);
        getContentPane().add(rbdP2B);
        rbdP2B.setBounds(120, 130, 149, 23);

        rbdP2C.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2C);
        rbdP2C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP2C.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2C.setText("c) Sojurner");
        rbdP2C.setBorder(null);
        getContentPane().add(rbdP2C);
        rbdP2C.setBounds(120, 160, 116, 23);

        lblPergunta3.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPergunta3.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta3.setText("Pergunta 3: Qual dessas sondas teve o primeiro drone de apoio a voar em Marte? ");
        getContentPane().add(lblPergunta3);
        lblPergunta3.setBounds(870, 60, 630, 21);

        rbdP3B.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3B);
        rbdP3B.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP3B.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3B.setText("b) Curiosity");
        rbdP3B.setBorder(null);
        getContentPane().add(rbdP3B);
        rbdP3B.setBounds(880, 130, 150, 23);

        rbdP3C.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3C);
        rbdP3C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP3C.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3C.setText("c) Opportunity");
        rbdP3C.setBorder(null);
        getContentPane().add(rbdP3C);
        rbdP3C.setBounds(880, 160, 150, 23);

        lblPergunta4.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPergunta4.setForeground(new java.awt.Color(74, 43, 23));
        lblPergunta4.setText("Pergunta 4: Qual foi a região designada para o pouso da sonda Curiosity em 2012? ");
        getContentPane().add(lblPergunta4);
        lblPergunta4.setBounds(110, 390, 630, 21);

        rbdP4A.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4A);
        rbdP4A.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP4A.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4A.setText("a) Cratera de Jazero");
        rbdP4A.setBorder(null);
        getContentPane().add(rbdP4A);
        rbdP4A.setBounds(130, 430, 190, 23);

        rbdP4B.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4B);
        rbdP4B.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP4B.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4B.setText("b) Ares Vallis");
        rbdP4B.setBorder(null);
        getContentPane().add(rbdP4B);
        rbdP4B.setBounds(130, 460, 160, 23);

        rbdP4C.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4C);
        rbdP4C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP4C.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4C.setText("c) Cratera Gale");
        rbdP4C.setBorder(null);
        rbdP4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdP4CActionPerformed(evt);
            }
        });
        getContentPane().add(rbdP4C);
        rbdP4C.setBounds(130, 490, 170, 23);

        lblPergunta5.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPergunta5.setForeground(new java.awt.Color(74, 43, 23));
        lblPergunta5.setText("Pergunta 5: Em 2020 quantas sondas foram lançadas a marte? ");
        getContentPane().add(lblPergunta5);
        lblPergunta5.setBounds(870, 390, 500, 21);

        rbdP5A.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5A);
        rbdP5A.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP5A.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5A.setText("a) 4");
        rbdP5A.setBorder(null);
        getContentPane().add(rbdP5A);
        rbdP5A.setBounds(880, 420, 110, 23);

        rbdP5B.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5B);
        rbdP5B.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP5B.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5B.setText("b) 1");
        rbdP5B.setBorder(null);
        getContentPane().add(rbdP5B);
        rbdP5B.setBounds(880, 450, 110, 23);

        rbdP5C.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5C);
        rbdP5C.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP5C.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5C.setText("c) 3");
        rbdP5C.setBorder(null);
        getContentPane().add(rbdP5C);
        rbdP5C.setBounds(880, 480, 110, 23);

        rbdP3A.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3A);
        rbdP3A.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rbdP3A.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3A.setText("a) Perseverance");
        rbdP3A.setBorder(null);
        getContentPane().add(rbdP3A);
        rbdP3A.setBounds(880, 100, 149, 23);

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblTotalRespo);
        lblTotalRespo.setBounds(189, 692, 203, 0);

        lblResposta.setBackground(new java.awt.Color(74, 43, 23));
        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(35, 588, 107, 0);

        lblMostrarResultado.setBackground(new java.awt.Color(74, 43, 23));
        lblMostrarResultado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMostrarResultado.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblMostrarResultado);
        lblMostrarResultado.setBounds(511, 698, 389, 31);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1240, 670, 150, 60);

        lblacertos.setBackground(new java.awt.Color(74, 43, 23));
        lblacertos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblacertos.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblacertos);
        lblacertos.setBounds(35, 698, 246, 0);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuarActionPerformed
    {//GEN-HEADEREND:event_btnContinuarActionPerformed
         if (rbdP2A.isSelected())
        {
            resp2 = "acerto";
            Estaticos.SOMAACERTOS++; 
        }
        else
        {
            resp2 = "erro";
        }    
      
        
        if (rbdP3A.isSelected())
        {
            resp3 = "acerto";
            Estaticos.SOMAACERTOS++; 
        }
        else
        {
            resp3 = "erro";
        } 
        
        
        if (rbdP4C.isSelected())
        {
            resp4 = "acerto";
            Estaticos.SOMAACERTOS++; 
        }
        else
        {
            resp4 = "erro";
        } 
        
        
        if (rbdP5C.isSelected())
        {
            resp5 = "acerto";
            Estaticos.SOMAACERTOS++; 
        }
        else
        {
            resp5 = "erro";
        }    
        
        Controle controle = new Controle(Estaticos.NOME, Estaticos.RESP1, resp2, resp3, resp4, resp5);

        Estaticos.SOMA++;
        lblTotalRespo.setText("Total de respondentes: " + Estaticos.SOMA);
        Estaticos.TEXTO = lblTotalRespo.getText();
        
        lblacertos.setText("Seu total de acerto foi: " + Estaticos.SOMAACERTOS);
        Estaticos.ACERTOS = lblacertos.getText();
        
        frmFinal frmF = new frmFinal(null, true);
        this.setVisible(false);
        frmF.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void rbdP4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdP4CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdP4CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPergunta2 dialog = new frmPergunta2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup gbtnP2;
    private javax.swing.ButtonGroup gbtnP3;
    private javax.swing.ButtonGroup gbtnP4;
    private javax.swing.ButtonGroup gbtnP5;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblMostrarResultado;
    private javax.swing.JLabel lblPergunta2;
    private javax.swing.JLabel lblPergunta3;
    private javax.swing.JLabel lblPergunta4;
    private javax.swing.JLabel lblPergunta5;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JLabel lblacertos;
    private javax.swing.JRadioButton rbdP2A;
    private javax.swing.JRadioButton rbdP2B;
    private javax.swing.JRadioButton rbdP2C;
    private javax.swing.JRadioButton rbdP3A;
    private javax.swing.JRadioButton rbdP3B;
    private javax.swing.JRadioButton rbdP3C;
    private javax.swing.JRadioButton rbdP4A;
    private javax.swing.JRadioButton rbdP4B;
    private javax.swing.JRadioButton rbdP4C;
    private javax.swing.JRadioButton rbdP5A;
    private javax.swing.JRadioButton rbdP5B;
    private javax.swing.JRadioButton rbdP5C;
    // End of variables declaration//GEN-END:variables
}
